services:
  llen:
    build:
      context: .
    container_name: llen-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: llen-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: AD-Task-3
    ports:
      - "23567:27017"
    volumes:
      - llen-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: llen-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: AD-Task-3
    ports:
      - "5555:5432"
    volumes:
      - llen-postgresql:/data/db/postgresql

volumes:
  llen-mongodb:
    driver: local
  llen-postgresql:
    driver: local
